# Generated by Django 6.0.7 on 2026-09-24 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_character_arena_floor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('job', models.CharField(choices=[('grappler', '拳闘士'), ('warrior', '重戦士'), ('hunter', '狩人'), ('wizard', 'ウィザード'), ('priest', 'プリースト'), ('wanderer', '放浪人'), ('assassin', '暗殺者')], max_length=20)),
                ('attribute', models.CharField(choices=[('fire', '炎'), ('water', '水'), ('grass', '草'), ('rock', '岩'), ('light', '光'), ('dark', '闇'), ('neutral', '無'), ('none', 'なし')], default='neutral', max_length=20)),
                ('skill_type', models.CharField(choices=[('physical', '物理'), ('magic', '魔法'), ('support', '補助'), ('heal', '回復'), ('physical_support', '物理/補助'), ('heal_support', '回復/補助'), ('passive', 'パッシブ')], max_length=30)),
                ('mp_cost', models.PositiveIntegerField(default=0)),
                ('activation_rate', models.PositiveSmallIntegerField(default=80)),
                ('is_passive', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SkillPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.PositiveSmallIntegerField()),
                ('use_count', models.PositiveIntegerField(default=1)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_presets', to='accounts.character')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presets', to='battle.skill')),
            ],
            options={
                'ordering': ['slot'],
                'constraints': [models.UniqueConstraint(fields=('character', 'slot'), name='unique_character_skill_slot')],
            },
        ),
    ]
