# Generated by Django 6.0.7 on 2026-09-24 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0002_add_initial_skills'),
        ('inventory', '0002_item_market_sellable_item_npc_purchasable_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enemy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('level', models.PositiveIntegerField(default=1)),
                ('max_hp', models.PositiveIntegerField(default=30)),
                ('max_mp', models.PositiveIntegerField(default=10)),
                ('strength', models.PositiveIntegerField(default=5)),
                ('intelligence', models.PositiveIntegerField(default=5)),
                ('dexterity', models.PositiveIntegerField(default=5)),
                ('agility', models.PositiveIntegerField(default=5)),
                ('vitality', models.PositiveIntegerField(default=5)),
                ('luck', models.PositiveIntegerField(default=5)),
                ('attribute', models.CharField(choices=[('fire', '炎'), ('water', '水'), ('grass', '草'), ('rock', '岩'), ('light', '光'), ('dark', '闇'), ('neutral', '無'), ('none', 'なし')], default='neutral', max_length=20)),
                ('exp_min', models.PositiveIntegerField(default=7)),
                ('exp_max', models.PositiveIntegerField(default=12)),
            ],
        ),
        migrations.CreateModel(
            name='FloorDropItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.PositiveIntegerField(help_text='探索階層')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floor_drops', to='inventory.item')),
            ],
            options={
                'ordering': ['floor', 'item__name'],
                'constraints': [models.UniqueConstraint(fields=('floor', 'item'), name='unique_floor_drop_item')],
            },
        ),
    ]
