# Generated by Django 6.0.7 on 2026-10-05 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0003_enemy_floordropitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='enemy',
            name='floor',
            field=models.PositiveIntegerField(default=1, help_text='出現する探索階層'),
        ),
        migrations.AddField(
            model_name='enemy',
            name='is_boss',
            field=models.BooleanField(default=False),
        ),
    ]
