# Generated by Django 6.0.7 on 2026-10-06 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0005_add_initial_enemies'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='floordropitem',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='floordropitem',
            name='unique_floor_drop_item',
        ),
        migrations.AddField(
            model_name='floordropitem',
            name='drop_weight',
            field=models.PositiveIntegerField(default=100, help_text='ドロップ候補内での抽選重み。小さいほど出にくい。'),
        ),
    ]
