# Generated by Django 6.0.7 on 2026-08-18 00:38

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_id', models.CharField(help_text='ログイン用の固有ID', max_length=20, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('level', models.PositiveIntegerField(default=1, help_text='キャラクターの現在レベル')),
                ('exp', models.PositiveIntegerField(default=0, help_text='現在保持している経験値')),
                ('reincarnation_count', models.PositiveIntegerField(default=0, help_text='転生した回数')),
                ('max_hp', models.PositiveIntegerField(default=30, help_text='キャラクターの最大HP')),
                ('current_hp', models.PositiveIntegerField(default=30, help_text='キャラクターの現在HP')),
                ('max_mp', models.PositiveIntegerField(default=10, help_text='キャラクターの最大MP')),
                ('current_mp', models.PositiveIntegerField(default=10, help_text='キャラクターの現在MP')),
                ('strength', models.PositiveIntegerField(default=5, help_text='筋力（STR）')),
                ('intelligence', models.PositiveIntegerField(default=5, help_text='知力（INT）')),
                ('dexterity', models.PositiveIntegerField(default=5, help_text='器用さ（DEX）')),
                ('agility', models.PositiveIntegerField(default=5, help_text='素早さ（AGI）')),
                ('vitality', models.PositiveIntegerField(default=5, help_text='体力（VIT）')),
                ('luck', models.PositiveIntegerField(default=5, help_text='運（LUK）')),
                ('fire', models.PositiveIntegerField(default=0, help_text='火属性値')),
                ('water', models.PositiveIntegerField(default=0, help_text='水属性値')),
                ('grass', models.PositiveIntegerField(default=0, help_text='草属性値')),
                ('rock', models.PositiveIntegerField(default=0, help_text='岩属性値')),
                ('light', models.PositiveIntegerField(default=0, help_text='光属性値')),
                ('dark', models.PositiveIntegerField(default=0, help_text='闇属性値')),
                ('gold', models.PositiveIntegerField(default=0, help_text='現在の所持金')),
                ('max_stamina', models.PositiveIntegerField(default=100, help_text='キャラクターの最大スタミナ')),
                ('current_stamina', models.PositiveIntegerField(default=100, help_text='キャラクターの現在スタミナ')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='キャラクター作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='キャラクター情報更新日時')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='character', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
