# Generated by Django 6.0.7 on 2026-07-30 03:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('level', models.PositiveIntegerField(default=1, help_text='キャラクターの現在レベル')),
                ('exp', models.PositiveIntegerField(default=0, help_text='現在保持している経験値')),
                ('reincarnation_count', models.PositiveIntegerField(default=0, help_text='転生した回数')),
                ('max_hp', models.PositiveIntegerField(default=30, help_text='キャラクターの最大HP')),
                ('current_hp', models.PositiveIntegerField(default=30, help_text='キャラクターの現在HP')),
                ('max_mp', models.PositiveIntegerField(default=10, help_text='キャラクターの最大MP')),
                ('current_mp', models.PositiveIntegerField(default=10, help_text='キャラクターの現在MP')),
                ('strength', models.PositiveIntegerField(default=5, help_text='筋力（STR）')),
                ('intelligence', models.PositiveIntegerField(default=5, help_text='知力（INT）')),
                ('dexterity', models.PositiveIntegerField(default=5, help_text='器用さ（DEX）')),
                ('agility', models.PositiveIntegerField(default=5, help_text='素早さ（AGI）')),
                ('vitality', models.PositiveIntegerField(default=5, help_text='体力（VIT）')),
                ('luck', models.PositiveIntegerField(default=5, help_text='運（LUK）')),
                ('fire', models.PositiveIntegerField(default=0, help_text='火属性値')),
                ('water', models.PositiveIntegerField(default=0, help_text='水属性値')),
                ('grass', models.PositiveIntegerField(default=0, help_text='草属性値')),
                ('rock', models.PositiveIntegerField(default=0, help_text='岩属性値')),
                ('light', models.PositiveIntegerField(default=0, help_text='光属性値')),
                ('dark', models.PositiveIntegerField(default=0, help_text='闇属性値')),
                ('gold', models.PositiveIntegerField(default=0, help_text='現在の所持金')),
                ('max_stamina', models.PositiveIntegerField(default=100, help_text='キャラクターの最大スタミナ')),
                ('current_stamina', models.PositiveIntegerField(default=100, help_text='キャラクターの現在スタミナ')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='キャラクター作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='キャラクター情報更新日時')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='character', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
