# Generated by Django 6.0.7 on 2026-09-17 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='job',
            field=models.CharField(choices=[('grappler', '拳闘士'), ('warrior', '重戦士'), ('hunter', '狩人'), ('wizard', 'ウィザード'), ('priest', 'プリースト'), ('wanderer', '放浪人'), ('assassin', '暗殺者')], default='wanderer', help_text='キャラクターの職業', max_length=20),
        ),
        migrations.AddField(
            model_name='character',
            name='race',
            field=models.CharField(choices=[('human', 'ヒューマン'), ('elf', 'エルフ'), ('dwarf', 'ドワーフ'), ('dragonia', 'ドラゴニア'), ('witch', 'ウィッチ'), ('fairy', 'フェアリー'), ('demonia', 'デモニア')], default='human', help_text='キャラクターの種族', max_length=20),
        ),
    ]
