# Generated by Django 6.0.7 on 2026-09-17 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_character_job_character_race'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='exploration_cooldown_reduced_until',
            field=models.DateTimeField(blank=True, help_text='探索クールタイム短縮効果の終了日時', null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='last_explored_at',
            field=models.DateTimeField(blank=True, help_text='最後に探索した日時', null=True),
        ),
    ]
