# Generated by Django 6.0.7 on 2026-09-17 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_character_exploration_cooldown_reduced_until_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='exploration_cooldown_until',
            field=models.DateTimeField(blank=True, help_text='現在の探索クールタイム終了日時', null=True),
        ),
    ]
