# Generated by Django 6.0.7 on 2026-09-18 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_character_exploration_cooldown_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='arena_floor',
            field=models.PositiveIntegerField(default=1, help_text='現在の闘技場階層'),
        ),
    ]
