# Generated by Django 6.0.7 on 2026-09-28 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_character_arena_floor'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='dark_growth_weight',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='character',
            name='fire_growth_weight',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='character',
            name='grass_growth_weight',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='character',
            name='light_growth_weight',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='character',
            name='rock_growth_weight',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='character',
            name='water_growth_weight',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
