# Generated by Django 6.0.7 on 2026-09-29 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_character_arena_last_result_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='arena_next_floor_unlocked',
            field=models.BooleanField(default=False, help_text='次の闘技場階層への挑戦が解禁されているか'),
        ),
    ]
