# Generated by Django 6.0.7 on 2026-10-07 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_character_dark_growth_weight_and_more'),
        ('accounts', '0009_character_arena_next_floor_unlocked'),
    ]

    operations = [
    ]
