# Generated by Django 6.0.7 on 2026-10-08 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_merge_20261007_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='character_image_id',
            field=models.PositiveIntegerField(blank=True, help_text='使用するキャラクター画像番号', null=True),
        ),
    ]
