# Generated by Django 6.0.7 on 2026-08-18 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='アイテム名', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='アイテムの説明')),
                ('category', models.CharField(choices=[('consumable', '消耗品'), ('equipment', '装備品'), ('material', '素材'), ('key_item', '重要アイテム')], help_text='アイテムの種類', max_length=20)),
                ('buy_price', models.PositiveIntegerField(default=0, help_text='購入価格')),
                ('sell_price', models.PositiveIntegerField(default=0, help_text='売却価格')),
                ('is_usable', models.BooleanField(default=False, help_text='使用可能なアイテムか')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='所持数')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='accounts.character')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_entries', to='inventory.item')),
            ],
            options={
                'ordering': ['item__category', 'item__name'],
                'constraints': [models.UniqueConstraint(fields=('character', 'item'), name='unique_character_item'), models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='inventory_quantity_gte_1')],
            },
        ),
    ]
