# Generated by Django 6.0.7 on 2026-09-16 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='market_sellable',
            field=models.BooleanField(default=True, help_text='フリマへ出品できるか'),
        ),
        migrations.AddField(
            model_name='item',
            name='npc_purchasable',
            field=models.BooleanField(default=False, help_text='NPCショップから購入できるか'),
        ),
        migrations.AddField(
            model_name='item',
            name='npc_sellable',
            field=models.BooleanField(default=True, help_text='NPCショップへ売却できるか'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('consumable', '消耗品'), ('equipment', '装備品'), ('material', '素材'), ('key_item', '重要アイテム'), ('system', 'システム')], help_text='アイテムの種類', max_length=20),
        ),
    ]
