# Generated by Django 6.0.7 on 2026-10-06 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_character_dark_growth_weight_and_more'),
        ('inventory', '0002_item_market_sellable_item_npc_purchasable_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(choices=[('E', 'E'), ('D', 'D'), ('C', 'C'), ('B', 'B'), ('A', 'A'), ('S', 'S')], default='E', max_length=1)),
                ('slot', models.CharField(choices=[('weapon', '武器'), ('head', '頭具'), ('armor', '防具'), ('feet', '足具'), ('accessory', 'アクセサリー')], max_length=20)),
                ('style', models.CharField(choices=[('physical', '物理型'), ('magic', '魔法型')], help_text='物理型または魔法型', max_length=20)),
                ('base_battle_power', models.PositiveIntegerField(help_text='未強化時の装備戦闘力')),
                ('strength_rate', models.PositiveSmallIntegerField(default=0)),
                ('intelligence_rate', models.PositiveSmallIntegerField(default=0)),
                ('dexterity_rate', models.PositiveSmallIntegerField(default=0)),
                ('agility_rate', models.PositiveSmallIntegerField(default=0)),
                ('vitality_rate', models.PositiveSmallIntegerField(default=0)),
                ('luck_rate', models.PositiveSmallIntegerField(default=0)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_data', to='inventory.item')),
            ],
        ),
        migrations.CreateModel(
            name='OwnedEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enhancement_level', models.PositiveIntegerField(default=0)),
                ('battle_power', models.PositiveIntegerField()),
                ('is_equipped', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_equipments', to='accounts.character')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_instances', to='inventory.equipment')),
            ],
        ),
    ]
