# Generated by Django 6.0.7 on 2026-10-06 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_item_market_sellable_item_npc_purchasable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='cooldown_reduction_days',
            field=models.PositiveIntegerField(blank=True, help_text='探索・闘技場のCT短縮効果日数。対象外アイテムは未設定', null=True),
        ),
    ]
