# Generated by Django 6.0.7 on 2026-10-07 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_equipment_ownedequipment'),
        ('inventory', '0003_item_cooldown_reduction_days'),
    ]

    operations = [
    ]
