# Generated by Django 6.0.7 on 2026-09-10 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.PositiveIntegerField(default=0, help_text='現在の在庫数')),
                ('sale_price', models.PositiveIntegerField(blank=True, help_text='ショップ専用価格。未設定ならItem.buy_priceを使用', null=True)),
                ('is_available', models.BooleanField(default=True, help_text='ショップで販売中か')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shop_stock', to='inventory.item')),
            ],
            options={
                'ordering': ['item__category', 'item__name'],
            },
        ),
    ]
