# Generated by Django 6.0.7 on 2026-09-16 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers'),
        ('inventory', '0002_item_market_sellable_item_npc_purchasable_and_more'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.PositiveIntegerField(help_text='1個あたりの販売価格')),
                ('status', models.CharField(choices=[('listed', '出品中'), ('sold', '売却済み'), ('cancelled', 'キャンセル')], default='listed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sold_at', models.DateTimeField(blank=True, null=True)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='market_purchases', to='accounts.character')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='market_listings', to='inventory.item')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_listings', to='accounts.character')),
            ],
        ),
    ]
